add_executable(System.Convert.Test ${UNITS_TEST_PATH}/System.Convert.Test.cpp ${CommonSrc})
add_executable(System.IO.FileStream.Test ${UNITS_TEST_PATH}/System.IO.FileStream.Test.cpp ${CommonSrc})
add_executable(System.IO.MemoryMappedFiles.Recv.Test ${UNITS_TEST_PATH}/System.IO.MemoryMappedFiles.Recv.Test.cpp ${CommonSrc})
add_executable(System.IO.MemoryMappedFiles.Send.Test ${UNITS_TEST_PATH}/System.IO.MemoryMappedFiles.Send.Test.cpp ${CommonSrc})
# add_executable(System.Socket.Client.Test ${UNITS_TEST_PATH}/System.Socket.Client.Test.cpp ${CommonSrc})
# add_executable(System.Socket.Server.Test ${UNITS_TEST_PATH}/System.Socket.Server.Test.cpp ${CommonSrc})
add_executable(System.Threading.Thread.Test ${UNITS_TEST_PATH}/System.Threading.Thread.Test.cpp ${CommonSrc})
include_directories(${THIRD_PARTY_PATH}/ftplib-4.0-1)
file(GLOB ftplib_src ${THIRD_PARTY_PATH}/ftplib-4.0-1/*.c)
add_executable(System.Net.FtpWebRequest.Test ${UNITS_TEST_PATH}/System.Net.FtpWebRequest.Test.cpp  ${ftplib_src})
