add_executable(System.Convert.Test ${UNITS_TEST_PATH}/System.Convert.Test.cpp ${CommonSrc})
add_executable(System.IO.FileStream.Test ${UNITS_TEST_PATH}/System.IO.FileStream.Test.cpp ${CommonSrc})
add_executable(System.IO.MemoryMappedFiles.Recv.Test ${UNITS_TEST_PATH}/System.IO.MemoryMappedFiles.Recv.Test.cpp ${CommonSrc})
add_executable(System.IO.MemoryMappedFiles.Send.Test ${UNITS_TEST_PATH}/System.IO.MemoryMappedFiles.Send.Test.cpp ${CommonSrc})
add_executable(System.Socket.Tcp.Client.Test ${UNITS_TEST_PATH}/System.Socket.Tcp.Client.Test.cpp ${CommonSrc})
add_executable(System.Socket.Tcp.Server.Test ${UNITS_TEST_PATH}/System.Socket.Tcp.Server.Test.cpp ${CommonSrc})
add_executable(System.Socket.Udp.Client.Unicast..Test ${UNITS_TEST_PATH}/System.Socket.Udp.Client.Unicast.Test.cpp ${CommonSrc})
add_executable(System.Socket.Udp.Client.Multicast.Test ${UNITS_TEST_PATH}/System.Socket.Udp.Client.Multicast.Test.cpp ${CommonSrc})
add_executable(System.Socket.Udp.Client.Broadcast.Test ${UNITS_TEST_PATH}/System.Socket.Udp.Client.Broadcast.Test.cpp ${CommonSrc})
add_executable(System.Socket.Udp.Server.Test ${UNITS_TEST_PATH}/System.Socket.Udp.Server.Test.cpp ${CommonSrc})
add_executable(System.Threading.Thread.Test ${UNITS_TEST_PATH}/System.Threading.Thread.Test.cpp ${CommonSrc})

include_directories(${THIRD_PARTY_PATH}/ftplib-4.0-1)
file(GLOB ftplib_src ${THIRD_PARTY_PATH}/ftplib-4.0-1/*.c)
add_library(ftplib ${ftplib_src})
add_executable(System.Net.FtpWebRequest.Test ${UNITS_TEST_PATH}/System.Net.FtpWebRequest.Test.cpp)
target_link_libraries(System.Net.FtpWebRequest.Test ${Lib_Path}/ftplib)