add_executable(System.Convert.Test ${UNITS_TEST_PATH}/System.Convert.Test.cpp)
add_executable(System.Console.Test ${UNITS_TEST_PATH}/System.Console.Test.cpp)
add_executable(System.IO.FileStream.Test ${UNITS_TEST_PATH}/System.IO.FileStream.Test.cpp)
add_executable(System.IO.Ini.Test ${UNITS_TEST_PATH}/System.IO.Ini.Test.cpp)
add_executable(System.IO.MemoryMappedFiles.Recv.Test ${UNITS_TEST_PATH}/System.IO.MemoryMappedFiles.Recv.Test.cpp)
add_executable(System.IO.MemoryMappedFiles.Send.Test ${UNITS_TEST_PATH}/System.IO.MemoryMappedFiles.Send.Test.cpp)
add_executable(System.Socket.Tcp.Client.Test ${UNITS_TEST_PATH}/System.Socket.Tcp.Client.Test.cpp)
add_executable(System.Socket.Tcp.Server.Test ${UNITS_TEST_PATH}/System.Socket.Tcp.Server.Test.cpp)
add_executable(System.Socket.Udp.Client.Unicast.Test ${UNITS_TEST_PATH}/System.Socket.Udp.Client.Unicast.Test.cpp)
add_executable(System.Socket.Udp.Client.Multicast.Test ${UNITS_TEST_PATH}/System.Socket.Udp.Client.Multicast.Test.cpp)
add_executable(System.Socket.Udp.Client.Broadcast.Test ${UNITS_TEST_PATH}/System.Socket.Udp.Client.Broadcast.Test.cpp)
add_executable(System.Socket.Udp.Server.Test ${UNITS_TEST_PATH}/System.Socket.Udp.Server.Test.cpp)
add_executable(System.Threading.Thread.Test ${UNITS_TEST_PATH}/System.Threading.Thread.Test.cpp)

add_executable(System.LinkList.Test ${UNITS_TEST_PATH}/System.LinkList.Test.cpp)
add_executable(System.List.Test ${UNITS_TEST_PATH}/System.List.Test.cpp)

include_directories(${THIRD_PARTY_PATH}/ftplib-4.0-1)
add_executable(System.Net.FtpWebRequest.Test ${UNITS_TEST_PATH}/System.Net.FtpWebRequest.Test.cpp)
target_link_libraries(System.Net.FtpWebRequest.Test ${Lib_Path}/ftplib)

include_directories(${THIRD_PARTY_PATH}/tinyxml-2-6-2)
add_executable(System.Xml.Test ${UNITS_TEST_PATH}/System.Xml.Test.cpp)
target_link_libraries(System.Xml.Test ${Lib_Path}/xmllib)